treebook/config/routes.rb
Treebook::Application.routes.draw do
  devise_for :users

  resources :statuses
  root to: 'statuses#index'

end

treebook/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :first_name, :last_name, :profile_name, :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

treebook/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Treebook</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="container">
		<div class="navbar navbar-inverse">
			<div class="navbar-inner">
				<div class="container">
						<!-- .btn-navbar is used as the toggle for collapsed navbar content -->
					    <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-responsive-collapse">
					        <span class="icon-bar"></span>
					        <span class="icon-bar"></span>
					        <span class="icon-bar"></span>
					    </a>
					    <a class="brand" href="#">Treebook</a>
					 
					    <!-- Everything you want hidden at 940px or less, place within here -->
					    <div class="nav-collapse collapse navbar-responsive-collapse">
					        <!-- .nav, .navbar-search, .navbar-form, etc -->
					        <ul class="nav">
					        	<li><% link_to "All Statuses", statuses_path %></li>
					        </ul>
					        <form class="navbar-search pull-left" action>
					        	<input type="text" class="search-query span2" placeholder="Search">
					        </form>
					    </div>
					    <!-- /.nav-collapse -->
				</div>
			</div>
			<!-- /navbar-inner -->
		</div>
		<!-- /navbar -->
		</div>	
	</div>
	<div class="container">
		<p class="notice"><%= notice %></p>
		<p class="alert"><%= alert %></p>

		<%= yield %>
	</div>


</body>
</html>